"""Default seed data for SVN MAKİNA (mirrors frontend mock.js)."""

IMG_BASE = "https://images.unsplash.com/"

DEFAULT_SETTINGS = {
    "brand": "SVN MAKİNA",
    "phone": "+90 555 000 00 00",
    "phone_raw": "+905550000000",
    "whatsapp": "905550000000",
    "email": "info@svnmakina.com",
    "email2": "svnmakina@gmail.com",
    "address_line": "İstasyon Mah. Sanayi Sitesi 28. Sk. No:21, 22100 Merkez / Edirne",
    "map_query": "Edirne Sanayi Sitesi",
    "instagram": "#",
    "facebook": "#",
    "linkedin": "#",
    "hero_title_tr": "SVN MAKİNA ÖZEL SERVİS",
    "hero_title_en": "SVN MAKİNA SPECIAL SERVICE",
    "hero_subtitle_tr": "SVN Makina olarak Türkiye genelinde uzman ekibimiz ile hızlı ve güvenilir iş makinesi bakım, onarım ve yedek parça hizmeti sağlamaktayız.",
    "hero_subtitle_en": "As SVN Makina, we provide fast and reliable heavy machinery maintenance, repair and spare parts services across Türkiye with our expert team.",
    "about_p1_tr": "SVN Makina olarak, Türkiye genelinde sunduğumuz profesyonel hizmetlerle fark yaratıyoruz. Uzman kadromuz, iş makineleri konusunda geniş bilgi ve deneyime sahiptir. Her türlü bakım, onarım ve yedek parça ihtiyaçlarınızda hızlı ve güvenilir çözümler sunuyoruz.",
    "about_p1_en": "As SVN Makina, we make a difference with the professional services we offer across Türkiye. Our expert staff has extensive knowledge and experience in heavy machinery. We provide fast and reliable solutions for all your maintenance, repair and spare parts needs.",
    "about_p2_tr": "Müşteri memnuniyetini önceliğimiz haline getiriyor, her aşamada şeffaf ve kaliteli hizmet sağlıyoruz. İhtiyaçlarınıza uygun çözümler geliştirerek makinelerinizin uzun ömürlü ve verimli çalışmasını sağlıyoruz.",
    "about_p2_en": "We make customer satisfaction our priority, providing transparent and quality service at every stage. We develop solutions tailored to your needs, ensuring your machines run long and efficiently.",
    "about_points_tr": [
        "Hızlı ve Güvenilir Teknik Servis",
        "Orijinal ve Garantili Yedek Parça Temini",
        "İhtiyaca Uygun İş Makinesi Kiralama",
        "Düzenli ve Kapsamlı Periyodik Bakım Hizmeti",
        "Avantajlı Fiyatlarla İş Makinesi Satışı",
    ],
    "about_points_en": [
        "Fast and Reliable Technical Service",
        "Original and Warranted Spare Parts",
        "Machinery Rental to Suit Your Needs",
        "Regular and Comprehensive Maintenance",
        "Machinery Sales at Advantageous Prices",
    ],
    # Editable images
    "hero_image": IMG_BASE + "photo-1742070122885-1b8aa9726d1a?crop=entropy&cs=srgb&fm=jpg&q=85",
    "about_image": IMG_BASE + "photo-1742070122920-3480a94cfbbb?crop=entropy&cs=srgb&fm=jpg&q=85",
    # Editable section titles / taglines
    "hero_tagline_tr": "/// Teknik Servis Hizmetleri ///",
    "hero_tagline_en": "/// Technical Service ///",
    "about_tagline_tr": "/// HAKKIMIZDA ///",
    "about_tagline_en": "/// ABOUT US ///",
    "about_title_tr": "Neden Bizi Tercih Etmelisiniz?",
    "about_title_en": "Why Choose Us?",
    "services_tagline_tr": "/// HİZMETLERİMİZ ///",
    "services_tagline_en": "/// OUR SERVICES ///",
    "services_title_tr": "Size Nasıl Yardımcı Olabiliriz?",
    "services_title_en": "How Can We Help You?",
    "faq_tagline_tr": "/// S.S.S ///",
    "faq_tagline_en": "/// FAQ ///",
    "faq_title_tr": "Sıkça Sorulan Sorular",
    "faq_title_en": "Frequently Asked Questions",
    # Editable feature cards (3)
    "feature1_title_tr": "Uzman Kadro", "feature1_title_en": "Expert Team",
    "feature1_desc_tr": "Deneyimli ve eğitimli ekibimizle makineleriniz emin ellerde.",
    "feature1_desc_en": "Your machines are in safe hands with our experienced and trained team.",
    "feature2_title_tr": "Müşteri Memnuniyeti", "feature2_title_en": "Customer Satisfaction",
    "feature2_desc_tr": "İhtiyaçlarınıza odaklanan kaliteli hizmet anlayışıyla yanınızdayız.",
    "feature2_desc_en": "We are with you with a quality service approach focused on your needs.",
    "feature3_title_tr": "Hızlı Çözümler", "feature3_title_en": "Fast Solutions",
    "feature3_desc_tr": "Arızalara anında müdahale, hızlı ve etkili onarım garantisi sunuyoruz.",
    "feature3_desc_en": "We offer instant intervention to failures with fast and effective repair guarantee.",
    # Footer about text
    "footer_about_tr": "SVN Makina, Türkiye genelinde iş makineleri için hızlı ve güvenilir bakım, onarım ve yedek parça hizmeti sunar.",
    "footer_about_en": "SVN Makina offers fast and reliable maintenance, repair and spare parts services for heavy machinery across Türkiye.",
    # Maintenance mode
    "maintenance_mode": False,
    "maintenance_msg_tr": "Sitemiz kısa süreliğine bakımdadır. Kısa süre sonra tekrar hizmetinizdeyiz.",
    "maintenance_msg_en": "Our website is under maintenance. We will be back shortly.",
}

DEFAULT_SERVICES = [
    {"order": 1, "icon_key": "technical", "image_url": IMG_BASE + "photo-1615906655593-ad0386982a0f?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "İş Makinesi Teknik Servis", "title_en": "Machinery Technical Service",
     "desc_tr": "Türkiye genelinde iş makineleriniz için uzman teknik servis hizmeti sunuyoruz. Hızlı müdahale, kaliteli işçilik ve orijinal yedek parçalarla makinelerinizi güvenle çalıştırın.",
     "desc_en": "We offer expert technical service for your machinery across Türkiye. Run your machines safely with fast intervention, quality workmanship and original spare parts."},
    {"order": 2, "icon_key": "pricing", "image_url": IMG_BASE + "photo-1575281923032-f40d94ef6160?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "Servis Fiyatları 2025", "title_en": "Service Prices 2025",
     "desc_tr": "2025 servis, bakım ve yedek parça fiyatlarında uygun ve rekabetçi çözümler sunuyoruz. Kaliteli hizmeti en iyi fiyatlarla almak için bizimle iletişime geçin.",
     "desc_en": "We offer affordable and competitive solutions for 2025 service, maintenance and spare parts prices. Contact us to get quality service at the best prices."},
    {"order": 3, "icon_key": "parts", "image_url": IMG_BASE + "photo-1766650189458-bb0e7969ba5d?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "Yedek Parça", "title_en": "Spare Parts",
     "desc_tr": "İş makineleriniz için orijinal ve garantili yedek parça temin ediyoruz. Uzun ömürlü ve sorunsuz kullanım için kaliteli parçalarla makinelerinizi güvenle çalıştırın.",
     "desc_en": "We supply original and warranted spare parts for your machinery. Run your machines safely with quality parts for long and trouble-free use."},
    {"order": 4, "icon_key": "maintenance", "image_url": IMG_BASE + "photo-1565377167263-d29b5ac85479?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "Periyodik Bakım", "title_en": "Periodic Maintenance",
     "desc_tr": "Makinelerinizin verimli ve sorunsuz çalışması için düzenli bakım şart. Profesyonel ekibimizle periyodik bakım hizmeti sunarak olası arızaların önüne geçiyoruz.",
     "desc_en": "Regular maintenance is essential for your machines to run efficiently. We prevent possible failures with periodic maintenance by our professional team."},
    {"order": 5, "icon_key": "rental", "image_url": IMG_BASE + "photo-1620388640785-892616248ec8?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "Makine Kiralama", "title_en": "Machinery Rental",
     "desc_tr": "İhtiyacınıza uygun iş makinelerini uygun fiyatlarla kiralayın. Bakımlı ve güvenilir araçlarımızla projelerinize kesintisiz destek sunuyoruz.",
     "desc_en": "Rent machinery suitable for your needs at affordable prices. We provide uninterrupted support to your projects with our well-maintained and reliable vehicles."},
    {"order": 6, "icon_key": "sale", "image_url": IMG_BASE + "photo-1714627798569-b3e36d409c4b?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "2. El Satış", "title_en": "Used Machinery Sales",
     "desc_tr": "İkinci el iş makinelerinde en uygun fiyatlar ve geniş ürün yelpazesiyle satış hizmeti veriyoruz. Performanslı ve güvenilir makineler için bize ulaşın.",
     "desc_en": "We provide sales service with the most affordable prices and a wide range of used machinery. Contact us for high-performance and reliable machines."},
]

DEFAULT_TEAM = [
    {"order": 1, "name": "Hasan Savun", "title_tr": "Genel Müdür", "title_en": "General Manager",
     "phone": "+90 555 111 11 11", "phone_raw": "+905551111111", "email": "hasan@svnmakina.com",
     "avatar": "https://ui-avatars.com/api/?name=Hasan+Savun&background=E30613&color=fff&size=320&bold=true&font-size=0.4"},
    {"order": 2, "name": "Ali Savun", "title_tr": "Teknik Servis Müdürü", "title_en": "Technical Service Manager",
     "phone": "+90 555 222 22 22", "phone_raw": "+905552222222", "email": "ali@svnmakina.com",
     "avatar": "https://ui-avatars.com/api/?name=Ali+Savun&background=1a1a1a&color=fff&size=320&bold=true&font-size=0.4"},
    {"order": 3, "name": "Barış Eren Savun", "title_tr": "Satış & Kiralama Sorumlusu", "title_en": "Sales & Rental Manager",
     "phone": "+90 555 333 33 33", "phone_raw": "+905553333333", "email": "baris@svnmakina.com",
     "avatar": "https://ui-avatars.com/api/?name=Baris+Savun&background=E30613&color=fff&size=320&bold=true&font-size=0.4"},
]

DEFAULT_FAQS = [
    {"order": 1, "q_tr": "SVN Makina hangi hizmetleri sunar?", "q_en": "What services does SVN Makina offer?",
     "a_tr": "Teknik servis, periyodik bakım, orijinal yedek parça temini, iş makinesi kiralama ve 2. el satış gibi geniş bir hizmet yelpazesi sunuyoruz.",
     "a_en": "We offer a wide range of services including technical service, periodic maintenance, original spare parts supply, machinery rental and used machinery sales."},
    {"order": 2, "q_tr": "İş makineleri hangi sektörlerde kullanılır?", "q_en": "In which sectors is heavy machinery used?",
     "a_tr": "İnşaat, tarım, sanayi ve lojistik başta olmak üzere ağır yük kaldırma ve taşıma gerektiren tüm sektörlerde kullanılır.",
     "a_en": "It is used in all sectors requiring heavy lifting and handling, primarily construction, agriculture, industry and logistics."},
    {"order": 3, "q_tr": "Bakım ve onarım nasıl yapılır?", "q_en": "How is maintenance and repair done?",
     "a_tr": "Yağ değişimi, filtre kontrolü, hidrolik sistem denetimi ve lastik basınç ayarları gibi işlemler orijinal parçalarla uzman teknisyenlerimizce yapılır.",
     "a_en": "Operations such as oil change, filter check, hydraulic system inspection and tire pressure adjustment are performed with original parts by our expert technicians."},
    {"order": 4, "q_tr": "Periyodik bakım neden önemlidir?", "q_en": "Why is periodic maintenance important?",
     "a_tr": "Periyodik bakım makinelerin verimliliğini artırır, olası arızaların önüne geçer ve iş güvenliğini sağlar.",
     "a_en": "Periodic maintenance increases the efficiency of machines, prevents possible failures and ensures work safety."},
    {"order": 5, "q_tr": "Servis talebini nasıl oluşturabilirim?", "q_en": "How can I create a service request?",
     "a_tr": "Web sitemizdeki Servis Talep Formu'nu doldurabilir veya telefon/WhatsApp üzerinden bizimle iletişime geçebilirsiniz.",
     "a_en": "You can fill out the Service Request Form on our website or contact us by phone/WhatsApp."},
    {"order": 6, "q_tr": "SVN Makina'ya nasıl ulaşabilirim?", "q_en": "How can I reach SVN Makina?",
     "a_tr": "info@svnmakina.com e-posta adresinden veya iletişim sayfamızdaki telefon numaralarından bize kolayca ulaşabilirsiniz.",
     "a_en": "You can easily reach us via info@svnmakina.com or the phone numbers on our contact page."},
]

DEFAULT_ADMIN = {"username": "admin", "password": "admin123"}

DEFAULT_SLIDES = [
    {"order": 1, "image": IMG_BASE + "photo-1742070122885-1b8aa9726d1a?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "SVN MAKİNA ÖZEL SERVİS", "title_en": "SVN MAKİNA SPECIAL SERVICE",
     "subtitle_tr": "Türkiye genelinde uzman ekibimiz ile hızlı ve güvenilir iş makinesi bakım, onarım ve yedek parça hizmeti.",
     "subtitle_en": "Fast and reliable heavy machinery maintenance, repair and spare parts services across Türkiye.",
     "button_text_tr": "Bize Ulaşın", "button_text_en": "Contact Us", "button_link": "/iletisim", "active": True},
    {"order": 2, "image": IMG_BASE + "photo-1620388640785-892616248ec8?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "İŞ MAKİNESİ KİRALAMA", "title_en": "MACHINERY RENTAL",
     "subtitle_tr": "Bakımlı ve güvenilir araçlarımızla projelerinize kesintisiz destek sunuyoruz.",
     "subtitle_en": "We provide uninterrupted support to your projects with our well-maintained vehicles.",
     "button_text_tr": "Hizmetlerimiz", "button_text_en": "Our Services", "button_link": "/hizmetler", "active": True},
    {"order": 3, "image": IMG_BASE + "photo-1766650189458-bb0e7969ba5d?crop=entropy&cs=srgb&fm=jpg&q=85",
     "title_tr": "ORİJİNAL YEDEK PARÇA", "title_en": "ORIGINAL SPARE PARTS",
     "subtitle_tr": "İş makineleriniz için orijinal ve garantili yedek parça temin ediyoruz.",
     "subtitle_en": "We supply original and warranted spare parts for your machinery.",
     "button_text_tr": "Detaylar", "button_text_en": "Details", "button_link": "/hizmetler", "active": True},
]

DEFAULT_PAGES = [
    {"order": 1, "slug": "hakkimizda", "title_tr": "Hakkımızda", "title_en": "About Us",
     "image": IMG_BASE + "photo-1742070122920-3480a94cfbbb?crop=entropy&cs=srgb&fm=jpg&q=85",
     "content_tr": "SVN Makina olarak, Türkiye genelinde sunduğumuz profesyonel hizmetlerle fark yaratıyoruz. Uzman kadromuz iş makineleri konusunda geniş bilgi ve deneyime sahiptir. Her türlü bakım, onarım ve yedek parça ihtiyaçlarınızda hızlı ve güvenilir çözümler sunuyoruz.\n\nMüşteri memnuniyetini önceliğimiz haline getiriyor, her aşamada şeffaf ve kaliteli hizmet sağlıyoruz.",
     "content_en": "As SVN Makina, we make a difference with the professional services we offer across Türkiye. Our expert staff has extensive knowledge and experience in heavy machinery.\n\nWe make customer satisfaction our priority, providing transparent and quality service at every stage.",
     "show_in_menu": True},
]
